name: Deploy lambda

env:
  ARTIFACT_NAME: lambda_handler.zip

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: zip files
        run: |
          zip -r ${{ env.ARTIFACT_NAME }} ./*.py
          mkdir codedeploy_artifact
          mv ${{ env.ARTIFACT_NAME }} ./codedeploy_artifact

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copy Artifact to S3
        run: |
          aws s3 sync ./codedeploy_artifact s3://${{ secrets.S3_BUCKET_NAME }}

      - name: Update Function code
        run: |
          aws lambda update-function-code --function-name MyEmailSenderFunction --s3-bucket ${{ secrets.S3_BUCKET_NAME }} --s3-key ${{ env.ARTIFACT_NAME }}
